### PR TITLE
update out-of-date config-ssh.html

### PR DESCRIPTION
**Pull request by cwlbraa**
this could probably use more detail, but it's better than what was there before. 

Signed-off-by: Connor Braa <connor.braa@gmail.com>

### CODE REVIEW

**Comment by apeek4** [comment]
Thanks @cwlbraa! Are there any specific details you're hoping to see added to this?

**Comment by apeek4** [comment]
@cwlbraa Would these changes apply to all active versions or just 2.2?

**Comment by cwlbraa** [comment]
these should definitely be backported at least a version or two, I believe even old reference architectures recommend using iaas-provisioned lbs when they're available.

However, I'm not sure how far back in opsman the `Resource Config`/ Load Balacer boxes go. I'm also uncertain as to exactly when the HAProxy/consul instructions I removed became invalid, and how that might effect folks trying to configure ssh ingress on older PCFs without iaas-provisioned load balancers.

I think this version/iaas/feature combination complexity is likely why these docs are so out of date.

**Comment by cwlbraa** [comment]
@goonzoid @emalm @aaronhurley @shalako could y'all help with getting these straight? I'm not 1000% sure y'all are the best folks to ask, but I'm not sure who might be following the HAProxy/Consul/LB configuration interaction in the PAS tile across versions.

upon further discussion with @evanfarrar, too, though, we should get this on 2.2 for sure prior to ironing out the kinks with older versions.

**Comment by emalm** [comment]
@cwlbraa I haven't been directly involved in the SSH-proxy load-balancing configuration for a while now, but I think the HAProxy job in ERT/PAS now uses a BOSH link to configure itself to load-balance across the SSH proxy instances, instead of Consul-based templating.

In particular, [PAS 2.1.2 includes `haproxy` release v8.6.0](https://docs.pivotal.io/pivotalcf/2-1/pcf-release-notes/runtime-rn.html#2.1.2). That version of the HAProxy release [consumes a `tcp_backend` link of type `ssh_proxy`](https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/v8.6.0/jobs/haproxy/spec#L31-L33) and renders its instance entries and properties into its [TCP config template](https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/v8.6.0/jobs/haproxy/templates/haproxy.config.erb#L358-L366).

So I think Consul templating is now no longer used in 2.1. Since the separate `haproxy` release shows up first in [ERT 1.12.0](https://docs.pivotal.io/pivotalcf/1-12/pcf-release-notes/runtime-rn.html#1.12.0), that configuration is likely the case from 1.12 onward. Prior to that, I think that the haproxy job came from [cf-release](https://github.com/cloudfoundry-attic/cf-release/tree/v259/jobs/haproxy) and still used [Consul-based templating](https://github.com/cloudfoundry-attic/cf-release/blob/v259/jobs/haproxy/templates/haproxy.ctmpl.erb).

Hope that helps!

Best,
Eric

**Pull request merged**
