### PR TITLE
Add guide for troubleshooting Diego Windows

### PR DESCRIPTION
**Pull request by benmoss**
Hey,

Not sure if we should just merge this or if someone from the docs team wants to review this. It is a new page and I went ahead and added it to the `index.html`.

[#108893950](https://www.pivotaltracker.com/story/show/108893950)

Signed-off-by: Anthony Emengo <aemengo@pivotal.io>

### CODE REVIEW

**Comment by ljarzynski** [comment]
Hi @benmoss 

Thank you for submitting this PR! It's great to have this troubleshooting guide. We are currently reviewing the doc, and may reach out to you with a few questions.

**Comment by sbenario** [comment]
Based on feedback I think we're going to pull this back and instead publish it in our OSS repo here: https://github.com/cloudfoundry/diego-windows-release

**Comment by ljarzynski** [comment]
Okay @sbenario , thanks for letting us know. Should we go ahead close this PR without merging then?

**Comment by sbenario** [comment]
yup, sounds good

**Pull request closed without merging**
