### PR TITLE
Add disk space warning for percona migration

### PR DESCRIPTION
**Pull request by ywei2017**
We ran into space issue yesterday during the migration, and though the documentation should be more clear and in the front for disk space requirements.

### CODE REVIEW

**Comment by ljarzynski** [comment]
Thanks, @ywei2017

**Comment by pspinrad** [comment]
Hey @ywei2017 -- this guidance should be in the docs for all versions of PCF that support both MariaDB and Percona, e.g. PCF 2.2 and 2.3, right?  `master` branch currently just publishes to the pre-release pcf 2.4 docs.  Thanks!

**Comment by ywei2017** [comment]
Hi, @pspinrad , you are right, this guidance should be in the docs for all
versions supporting the DB migration. I didn't know the master branch is
only for the pre-release 2.4. Let me know if you want me to create separate
PRs for earlier releases.

Very much appreciate the good thought.
Yansheng

**Comment by pspinrad** [comment]
Hi Yansheng— thanks, I thought so, and it looks like @ljarzynski already cherry-picked the change over to 2.2 and 2.3 docs, so we are all good.

The way the docs versioning works is, we have branches for each currently supported version, and for the upcoming version (2.4, scheduled to release in December) we currently use the master branch.  Later, we will create a 2.4 branch based on master, and then master will become the pre-release 2.5 version docs.

I hope that makes sense, or let me know.

Thank you again for your contribution to the docs— we appreciate it!

Paul

**Pull request merged**
