### PR TITLE
Add details for improved Redirect URI configuration

### PR DESCRIPTION
**Pull request by sweinstein22**
for MultiFoundation Apps Manager support

### CODE REVIEW

**Comment by sweinstein22** [comment]
Feel free to reword things as you see fit, hopefully the general idea is clear. Happy to chat if there are any points that need clarification.

**Comment by paigecalvert** [comment]
Thank you @sweinstein22! We'll review and will reach out with any questions.

**Comment by jncd** [comment]
Hi @sweinstein22 

Could you provide an example of what a customer types into this Redirects URI text box? 
Would this work? (I'm assuming that I have to type the two asterisks as shown.) 

> `https://apps.example.com/**, https://apps.example2.com/**`

http://docs-pcf-staging.cfapps.io/pivotalcf/2-5/opsguide/configure-multi-foundation.html#pas (step 3)

**Comment by sweinstein22** [comment]
Hi @jncd , that would work! And yes, the two asterisks are required.

**Pull request merged**
