### PR TITLE
[RFC] Add docs for cell disk-space cleanup

### PR DESCRIPTION
**Pull request by glestaris**
Cell Disk-space cleanup is not currently very well documented. I'd like to contribute a new topic to ERT admin docs. It may be a bit too technical (especially the part of configuring the threshold) so please suggest any changes that you think will make these instructions more helpful.

# Next steps

[ ] Add link in https://github.com/pivotal-cf/docs-pcf-install/blob/59ef2c276cd81e01cfce0c605af6aebbdf13bb0e/_application_container_config.html.md.erb#L16 to this topic.

### CODE REVIEW

**Comment by seviet** [comment]
Thanks, @glestaris! I'll take a look at this today.

**Comment by seviet** [comment]
Hi George! Thank you so much for this pull request! I did a round of edits and clarifications. I didn't think the threshold section was too technical-- I think your calculation advice was useful. If you have any issues with my edits, please feel free to open up another pull request. I will also add a link to the ERT section of the install docs to this topic too.

**Comment by glestaris** [comment]
Thank you very much @seviet!! The changes look great.

Can I contribute parts of this doc to the CFF docs?

**Comment by seviet** [comment]
Hi @glestaris! Sure! Please feel free to submit a pull request to the OSS CF docs.

**Pull request merged**
